"""empty message

Revision ID: 3ebdad1f7c22
Revises: b59ebefc6d60
Create Date: 2018-07-25 15:04:47.355308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebdad1f7c22'
down_revision = 'b59ebefc6d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('accuracy', sa.String(length=140), nullable=True))
    op.add_column('test', sa.Column('reaction_time', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'reaction_time')
    op.drop_column('test', 'accuracy')
    # ### end Alembic commands ###
