"""empty message

Revision ID: b59ebefc6d60
Revises: fd78b723183f
Create Date: 2018-07-17 00:40:58.812511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59ebefc6d60'
down_revision = 'fd78b723183f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'data')
    # ### end Alembic commands ###
